config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :project_work_parties, only: %i[create update destroy]
  resources :work_parties
  resources :work_types
  resources :contacts
  resources :clients
  resources :projects
  devise_for :users
  root to: 'home#index'
end

app/models/work_party.rb
# == Schema Information
#
# Table name: work_parties
#
#  id           :integer          not null, primary key
#  name         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  work_type_id :integer          not null
#
# Indexes
#
#  index_work_parties_on_work_type_id  (work_type_id)
#
# Foreign Keys
#
#  work_type_id  (work_type_id => work_types.id)
#
class WorkParty < ApplicationRecord
  belongs_to :work_type
  has_many :project_work_parties
  has_many :projects, through: :project_work_parties

  delegate :name, to: :work_type, prefix: true, allow_nil: true
end

app/controllers/work_parties_controller.rb
# frozen_string_literal: true

# app/controllers/work_parties_controller
class WorkPartiesController < ApplicationController
  before_action :set_work_party, only: %i[show edit update destroy]

  # GET /work_parties or /work_parties.json
  def index
    @work_parties = WorkParty.all
  end

  # GET /work_parties/1 or /work_parties/1.json
  def show; end

  # GET /work_parties/new
  def new
    @work_party = WorkParty.new
  end

  # GET /work_parties/1/edit
  def edit; end

  # POST /work_parties or /work_parties.json
  def create
    @work_party = WorkParty.new(work_party_params)

    respond_to do |format|
      if @work_party.save
        format.html { redirect_to work_party_url(@work_party), notice: 'Work party was successfully created.' }
        format.json { render :show, status: :created, location: @work_party }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @work_party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_parties/1 or /work_parties/1.json
  def update
    respond_to do |format|
      if @work_party.update(work_party_params)
        format.html { redirect_to work_party_url(@work_party), notice: 'Work party was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_party }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @work_party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_parties/1 or /work_parties/1.json
  def destroy
    @work_party.destroy

    respond_to do |format|
      format.html { redirect_to work_parties_url, notice: 'Work party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_work_party
    @work_party = WorkParty.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def work_party_params
    params.require(:work_party).permit(:name, :work_type_id)
  end
end

app/helpers/work_parties_helper.rb
module WorkPartiesHelper
  def work_party_list
    WorkParty.all.collect do |party|
      ["#{party.name&.titleize} (#{party.work_type.name&.titleize})", party.id]
    end
  end
end

app/views/work_parties/_form.html.erb
<%= form_with(model: work_party) do |form| %>
  <% if work_party.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(work_party.errors.count, "error") %> prohibited this work_party from being saved:</h2>

      <ul>
        <% work_party.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table table-dark table-borderless">
    <tr>
      <td><%= form.label :name, class:'form-label' %></td>
      <td><%= form.text_field :name, placeholder: :name, class: 'form-control' %></td>
    </tr>
    <tr>
      <td><%= form.label :work_type_id, class: 'form-label' %></td>
      <td><%= form.select :work_type_id, work_types, {}, { class: 'form-select' } %></td>
    </tr>
  </table>

  <div>
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/work_parties/_work_parties_list.html.erb
<% if work_parties.exists? %>
  <div id="work_parties" class="text-capitalize list-group">
    <% work_parties.each do |work_party| %>
      <%= link_to work_party.name, work_party, class: 'text-decoration-none list-group-item list-group-item-action list-group-item-secondary' %>
    <% end %>
  </div>
<% else %>
  <p class="text-center text-secondary m-4">
    No any work parties!
  </p>
<% end %>

app/views/work_parties/_work_party.html.erb
<div id="<%= dom_id work_party %>">
  <table class="table table-dark table-bordered table-hover">
    <colgroup>
      <col style="width: 20%">
      <col style="width: auto">
    </colgroup>
    <tr>
      <td>Name</td>
      <td><%= work_party.name %></td>
    </tr>
    <tr>
      <td>Work Type</td>
      <td><%= work_party.work_type.name %></td>
    </tr>
  </table>

  <h3>Projects:</h3>

  <% if work_party.projects.blank? %>
    <div class="border border-secondary rounded">
      <p class="text-secondary text-center p-2">No any assigned projects!</p>
    </div>
  <% else %>
    <table class="table table-dark table-bordered table-hover text-capitalize">
      <thead>
      <tr>
        <td>Name</td>
        <td>Bill Status</td>
        <td>Bill Amount</td>
        <td>Payment Status</td>
      </tr>
      </thead>
      <tbody>
      <% work_party.project_work_parties.each do |pwp| %>
        <tr>
          <td><%= link_to pwp.project.name, pwp.project, class: 'text-light' %></td>
          <td><%= pwp.bill_amount %></td>
          <td><%= pwp.bill_status %></td>
          <td><%= pwp.payment_status %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/work_parties/edit.html.erb
<div class="col-md-8">
  <div>
    <%= link_to "↶ Back to list", work_types_path, class: 'btn btn-secondary mb-4' %>
  </div>

  <h3>Editing work party</h3>

  <%= render "form", work_party: @work_party %>
</div>

app/views/work_parties/index.html.erb
<p class="text-success"><%= notice %></p>

<div class="text-end">
  <%= link_to "Add work party", new_work_party_path, class: 'btn btn-success' %>
</div>
<h3>Work parties</h3>

<%= render 'work_parties/work_parties_list', work_parties: @work_parties %>

app/views/work_parties/new.html.erb
<div>
  <%= link_to "↶ Back to list", work_types_path, class: 'btn btn-secondary mb-4' %>
</div>
<h3>New work party</h3>

<div class="col-md-8 col-sm-12">
  <%= render "form", work_party: @work_party %>
</div>
<br>

app/views/work_parties/show.html.erb
<p class="text-success"><%= notice %></p>

<div class="d-flex py-2">
  <%= link_to "↶ Back to list", work_types_path, class: 'btn btn-secondary' %>
  <%= link_to "Edit", edit_work_party_path(@work_party), class: 'btn btn-primary px-4 ms-2 me-auto' %>
  <%= button_to "Delete", @work_party, method: :delete, class: 'btn btn-danger' %>
</div>

<%= render @work_party %>