config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :project_work_parties, only: %i[create update destroy]
  resources :work_parties
  resources :work_types
  resources :contacts
  resources :clients
  resources :projects
  devise_for :users
  root to: 'home#index'
end

app/models/client.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: clients
#
#  id         :integer          not null, primary key
#  active     :boolean          default(TRUE)
#  address    :string
#  contact    :string
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Client < ApplicationRecord
  has_many :contacts
  has_many :projects

  validates :name, presence: true
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

# app/controllers/clients_controller
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
    @contacts = @client.contacts
    @projects = @client.projects
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit; end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def client_params
    params.require(:client).permit(:name, :address, :contact, :active)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
  def client_list
    Client.all.collect { |client| [client.name, client.id] }
  end
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <table class="table table-dark table-bordered table-hover">
    <colgroup>
      <col style="width: 20%">
      <col style="width: auto">
    </colgroup>
    <tr>
      <td>Name:</td>
      <td><%= client.name %></td>
    </tr>

    <tr>
      <td>Address:</td>
      <td><%= client.address %></td>
    </tr>

    <tr>
      <td>Contact:</td>
      <td><%= client.contact %></td>
    </tr>

    <tr>
      <td>Status:</td>
      <td>
        <span class="<%= client.active? ? 'bg-success' : 'bg-secondary' %> rounded-pill px-4 py-1 text-light">
            <%= client.active? ? 'Active' : 'Inactive' %>

        </span>
      </td>
    </tr>

  </table>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div class="text-danger">
      <h3><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h3>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table table-dark table-borderless">
    <colgroup>
      <col style="width: 10%">
      <col style="width: auto">
    </colgroup>
    <tr>
      <td><%= form.label :name, class: 'form-label' %></td>
      <td><%= form.text_field :name, placeholder: :name, class: 'form-control' %></td>
    </tr>

    <tr>
      <td><%= form.label :address, class: 'form-label' %></td>
      <td><%= form.text_field :address, placeholder: :address, class: 'form-control' %></td>
    </tr>

    <tr>
      <td><%= form.label :contact, class: 'form-label' %></td>
      <td><%= form.text_field :contact, placeholder: :contact, class: 'form-control' %></td>
    </tr>
  </table>

  <div class="form-check-lg">
    <%= form.check_box :active, class: 'form-check-input' %>
    <%= form.label :active, class: 'form-check-label ms-2' %>
  </div>


  <div class="mt-4">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<%= link_to "↶ Back", @client, class: 'btn btn-secondary mb-4' %>
<%= link_to "Client list", clients_path, class: 'btn btn-primary mb-4' %>

<h3>Editing client</h3>

<%= render "form", client: @client %>

app/views/clients/index.html.erb
<p class="text-success"><%= notice %></p>

<h3>Clients</h3>
<div class="text-end">
  <%= link_to "New client", new_client_path, class: 'btn btn-success my-2' %>
</div>

<div id="clients" class="row mt-4">
  <% @clients.each do |client| %>
    <div class="col-sm-12 col-md-6 p-2">
      <%= link_to client, class: 'btn btn-light col-12 text-start' do %>
        <%= client.name %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/clients/new.html.erb
<div>
  <%= link_to "↶ Back to list", clients_path, class: 'btn btn-secondary mb-4' %>
</div>
<h3>Add New Client</h3>

<div class="col-md-8 col-sm-12">
  <%= render "form", client: @client %>
</div>
<br>

app/views/clients/show.html.erb
<p class="text-success"><%= notice %></p>

<div class="d-flex py-2">
  <%= link_to "↶ Back to list", clients_path, class: 'btn btn-secondary' %>
  <%= link_to "Edit", edit_client_path(@client), class: 'btn btn-primary px-4 ms-2 me-auto' %>
  <%= button_to "Delete", @client, method: :delete, class: 'btn btn-danger' %>
</div>

<%= render @client %>

<div class="my-4">
  <strong>Contacts:</strong>
  <% if @contacts.count.zero? %>
    <p class="text-secondary"> No any contacts.</p>
    <%= link_to 'Add Contact', new_contact_path, class: 'btn btn-success' %>
  <% else %>
    <%= render 'contacts/contact_list' %>
  <% end %>
</div>

<div class="my-4">
  <strong>Projects:</strong>
  <% if @projects.count.zero? %>
    <p class="text-secondary"> No any projects.</p>
    <%= link_to 'Add Project', new_project_path, class: 'btn btn-success' %>
  <% else %>
    <%= render 'projects/project_list' %>
  <% end %>
</div>