config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :project_work_parties, only: %i[create update destroy]
  resources :work_parties
  resources :work_types
  resources :contacts
  resources :clients
  resources :projects
  devise_for :users
  root to: 'home#index'
end

app/controllers/work_types_controller.rb
class WorkTypesController < ApplicationController
  before_action :set_work_type, only: %i[ show edit update destroy ]

  # GET /work_types or /work_types.json
  def index
    @work_types = WorkType.all
  end

  # GET /work_types/1 or /work_types/1.json
  def show
  end

  # GET /work_types/new
  def new
    @work_type = WorkType.new
  end

  # GET /work_types/1/edit
  def edit
  end

  # POST /work_types or /work_types.json
  def create
    @work_type = WorkType.new(work_type_params)

    respond_to do |format|
      if @work_type.save
        format.html { redirect_to work_type_url(@work_type), notice: "Work type was successfully created." }
        format.json { render :show, status: :created, location: @work_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @work_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_types/1 or /work_types/1.json
  def update
    respond_to do |format|
      if @work_type.update(work_type_params)
        format.html { redirect_to work_type_url(@work_type), notice: "Work type was successfully updated." }
        format.json { render :show, status: :ok, location: @work_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @work_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_types/1 or /work_types/1.json
  def destroy
    @work_type.destroy

    respond_to do |format|
      format.html { redirect_to work_types_url, notice: "Work type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_type
      @work_type = WorkType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_type_params
      params.require(:work_type).permit(:name)
    end
end

app/helpers/work_types_helper.rb
module WorkTypesHelper
  def work_types
    WorkType.all.collect { |w| [w.name, w.id] }
  end
end

app/views/work_types/_form.html.erb
<%= form_with(model: work_type) do |form| %>
  <% if work_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(work_type.errors.count, "error") %> prohibited this work_type from being saved:</h2>

      <ul>
        <% work_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table table-dark table-borderless">
    <tr>
      <td><%= form.label :name, class: 'form-label' %></td>
      <td><%= form.text_field :name, class: 'form-control', placeholder: :name %></td>
    </tr>
  </table>

  <div class="mt-4">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/work_types/_work_type.html.erb
<div id="<%= dom_id work_type %>">
  <p>
    <strong>Name:</strong>
    <%= work_type.name %>
  </p>

</div>

app/views/work_types/edit.html.erb
<div class="col-md-8">
  <div>
    <%= link_to "↶ Back to list", work_types_path, class: 'btn btn-secondary mb-4' %>
  </div>

  <h3>Editing work type</h3>

  <%= render "form", work_type: @work_type %>
</div>

app/views/work_types/index.html.erb
<p class="text-success"><%= notice %></p>

<h3>Work types</h3>
<div class="d-flex col-md-8 mb-4">
  <%= link_to "Add work type", new_work_type_path, class: 'btn btn-success' %>
  <%= link_to "Add work party", new_work_party_path, class: 'btn btn-primary ms-auto' %>
</div>

<div class="accordion col-md-8" id="accordionWorkTypes">
  <% @work_types.each_with_index do |work_type| %>
    <div class="accordion-item my-2">
      <h2 class="accordion-header" id="heading<%=work_type.id%>">
        <button class="accordion-button text-capitalize collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%=work_type.id%>" aria-expanded="false" aria-controls="collapse<%=work_type.id%>">
          <%= work_type.name %>
        </button>
      </h2>
      <div id="collapse<%=work_type.id%>" class="accordion-collapse collapse" aria-labelledby="heading<%=work_type.id%>" data-bs-parent="#accordionWorkTypes">
        <div class="accordion-body bg-dark">
          <!-- Action Buttons -->
          <div class="d-flex mb-2">
            <%= link_to edit_work_type_path(work_type), class: 'btn btn-primary ms-auto me-2 col-auto' do %>
              <i class="bi bi-pen"></i>
            <% end %>
            <%= button_to work_type, method: :delete, class: 'btn btn-danger' do %>
              <i class="bi bi-trash-fill"></i>
            <% end %>
          </div>
          <!-- /Action Buttons -->
          <%= render 'work_parties/work_parties_list', work_parties: work_type.work_parties %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/work_types/new.html.erb
<div>
  <%= link_to "↶ Back to list", work_types_path, class: 'btn btn-secondary mb-4' %>
</div>
<h3>New work type</h3>

<div class="col-md-8 col-sm-12">
  <%= render "form", work_type: @work_type %>
</div>
<br>

app/views/work_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @work_type %>

<div>
  <%= link_to "Edit this work type", edit_work_type_path(@work_type) %> |
  <%= link_to "Back to work types", work_types_path %>

  <%= button_to "Destroy this work type", @work_type, method: :delete %>
</div>